BulkyWeb/Areas/admin/Controllers/CompanyController.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models;
using Bulky.Models.ViewModels;
using Bulky.Utility;
using BulkyWeb.DataAccess.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.ObjectPool;
using NuGet.ProjectModel;
using System.Collections.Generic;
using System.Drawing.Drawing2D;

namespace BulkyWeb.Areas.admin.Controllers
{
    [Area("admin")]
/*    [Authorize(Roles = SD.Role_Admin)]
*/    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CompanyController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<CompanyTable> objCompanyList = _unitOfWork.company.GetAll().ToList();
            
             return View(objCompanyList);
        }

        public IActionResult Upsert(int? id)
        {
            //ViewBag.CategoryList = CategoryList;
            if (id == null || id==0)
            {
                return View(new CompanyTable());
            }
            else
            {
                //update
                CompanyTable companyobj = _unitOfWork.company.Get(u=>u.Id==id);
                return View(companyobj);
            }

        }

        [HttpPost]
        public IActionResult Upsert(CompanyTable obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Id == 0)
                {
                    _unitOfWork.company.Add(obj);
                }
                else
                {
                    _unitOfWork.company.Update(obj);
                }
                _unitOfWork.Save();
                TempData["success"] = "Company Created Successfully!";
                return RedirectToAction("Index");
            }
            else
            {
                return View(obj);
            }

        }
        

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<CompanyTable> objCompanyList = _unitOfWork.company.GetAll().ToList();
            return Json(new { data = objCompanyList });
        }

        [HttpDelete]

        public IActionResult Delete(int? id)
        {
            CompanyTable? companyfromdb = _unitOfWork.company.Get(u => u.Id == id); //works only with pk
            if (ModelState.IsValid)
            {
                _unitOfWork.company.Remove(companyfromdb);
                _unitOfWork.Save();
                return Json(new {success = true,message = "Deleted Succesfully"});
            }

            return View("Edit");
        }
        #endregion
    }
}

BulkyWeb/Areas/admin/Controllers/ProductController.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models;
using Bulky.Models.ViewModels;
using Bulky.Utility;
using BulkyWeb.DataAccess.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.ObjectPool;
using NuGet.ProjectModel;
using System.Collections.Generic;
using System.Drawing.Drawing2D;

namespace BulkyWeb.Areas.admin.Controllers
{
    [Area("admin")]
/*    [Authorize(Roles = SD.Role_Admin)]
*/    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<Product> objProductList = _unitOfWork.product.GetAll(includeProperties : "Category").ToList();
            
             return View(objProductList);
        }

        public IActionResult Upsert(int? id)
        {
            //ViewBag.CategoryList = CategoryList;

            ProductVM productVM = new()
            {
                CategoryList = _unitOfWork.category
                .GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Category_Id.ToString()
                }),
                Product = new Product()
            };

            if (id == null || id==0)
            {
                return View(productVM);
            }
            else
            {
                //update
                productVM.Product = _unitOfWork.product.Get(u=>u.Id==id);
                return View(productVM);
            }

        }

        [HttpPost]
        public IActionResult Upsert(ProductVM obj , IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRootPath, @"Images\product\");

                    if (!string.IsNullOrEmpty(obj.Product.ImageUrl))
                    {
                        //delete existing image
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.Trim('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using(var fileStream = new FileStream(Path.Combine(productPath, fileName),FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    obj.Product.ImageUrl = @"\Images\product\" + fileName;
                }

                if (obj.Product.Id == 0)
                {
                    _unitOfWork.product.Add(obj.Product);
                }
                else
                {
                    _unitOfWork.product.Update(obj.Product);
                }
                _unitOfWork.Save();
                TempData["success"] = "Record Created Successfully!";
                return RedirectToAction("Index");
            }
            else
            {
                ProductVM productVM = new()
                {
                    CategoryList = _unitOfWork.category.GetAll().Select(u => new SelectListItem
                    {
                        Text = u.Name,
                        Value = u.Category_Id.ToString()
                    }),
                    Product = new Product()
                };
                return View(productVM);
            }

        }
        

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Product> objProductList = _unitOfWork.product.GetAll(includeProperties: "Category").ToList();
            return Json(new { data = objProductList });
        }

/*        [HttpDelete]
*/
        public IActionResult Delete(int? id)
        {
            Product? productfromdb = _unitOfWork.product.Get(u => u.Id == id); //works only with pk
            if (ModelState.IsValid)
            {
                var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath,
                    productfromdb.ImageUrl.Trim('\\'));
                if (System.IO.File.Exists(oldImagePath))
                {
                    System.IO.File.Delete(oldImagePath);
                }
                _unitOfWork.product.Remove(productfromdb);
                _unitOfWork.Save();
                return Json(new {success = true,message = "Deleted Succesfully"});
            }

            return View("Edit");
        }
        #endregion
    }
}

BulkyWeb/Areas/admin/Views/Company/Index.cshtml
<partial name="_Notification" />


<div class="card shadow border-0 mt-2 mb-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2 text-center">
                    Comopanies List
                </h2>
            </div>
        </div>
    </div>

    <div class="card-body p-4">
        <div class="container">
            <div class="row pt-4 pb-3">
                <div class="col-12 text-end">
                    <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary"><i class="bi bi-plus-circle"></i> 
                        Create New Company
                    </a>
                </div>
            </div>
            <table id="tblData" class="table table-bordered table-stripped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Address</th>
                        <th>City</th>
                        <th>State</th>
                        <th>PhoneNumber</th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>


                    @section Scripts{
                        <script src="~/js/company.js"></script>
                    }

BulkyWeb/Areas/admin/Views/Company/Upsert.cshtml
@model CompanyTable

<partial name="_Notification" />


<div class="card shadow border-0 mt--4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2 text-center">
                    @(Model.Id!=0?"Update":"Create") Company
                </h2>
            </div>
        </div>
    </div>

    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />

            <div class="row">
                <div class="col-12">
                    <div class="border p-3">
                        <div row pb-2>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Name" type="text" class="form-control border-0 shadow" />
                            <label asp-for="Name" class="ms-2"></label>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="py-2 col-12">
                            <label asp-for="PhoneNumber" class="ms-2 text-muted"></label>
                            <textarea asp-for="PhoneNumber" type="text" class="form-control border-0 shadow"></textarea>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="StreetAddress" type="text" class="form-control border-0 shadow" />
                            <label asp-for="StreetAddress" class="ms-2"></label>
                            <span asp-validation-for="StreetAddress" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="City" type="text" class="form-control border-0 shadow" />
                            <label asp-for="City" class="ms-2"></label>
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="State" type="text" class="form-control border-0 shadow" />
                            <label asp-for="State" class="ms-2"></label>
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="PostalCode" type="text" class="form-control border-0 shadow" />
                            <label asp-for="PostalCode" class="ms-2"></label>
                            <span asp-validation-for="PostalCode" class="text-danger"></span>
                        </div>
                        <div class="row">
                            <div class="col-6 col-md-3">
                                <button type="submit" class="btn btn-primary form-control">Save</button>
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Product" asp-action="Index" class="form-control btn btn-light btn-outline-secondary border">Back To List</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </form>
    </div>
</div>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}